services:
  searxng:
    image: searxng/searxng:latest
    container_name: searxng
    env_file:
      - .env
    environment:
      - SEARXNG_BASE_URL=http://127.0.0.1:8888/
    ports:
      - "127.0.0.1:8888:8080"
    volumes:
      - ./config:/etc/searxng:rw
    dns:
      - 8.8.8.8
      - 1.1.1.1
    extra_hosts:
      - "host.docker.internal:host-gateway"
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
    restart: unless-stopped
